### ISSUE TITLE
[Suggestion] Add ability for CurseForge Update 

### ISSUE THREAD

**Issue by yodaluca23** [DeDiamondPro/Auto-Updater#1]
Just like it is now except you can paste either CurseForge or GitHub links, I think you may be able to use the Core API or the Upload API... https://docs.curseforge.com/#an-introduction-to-curseforge
https://support.curseforge.com/en/support/solutions/articles/9000197321-curseforge-upload-api

**Comment by PigDan20** [comment]
Is this possible to add? I agree that this would be a very useful feature.

**Comment by DeDiamondPro** [comment]
The curseforge API requires an API-key that you need to apply for to get, this makes it unpractical to use in something like this
